### ISSUE TITLE
ENOMEM: Server hangs up

### ISSUE THREAD

**Issue by hezedu** [linux-remote/linux-remote#242]
Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:548:9)
    at startServer (/opt/linux-remote/node_modules/@linux-remote/session-store/src/start-server.js:4:10)
    at spwanServer (/opt/linux-remote/node_modules/@linux-remote/session-store/index.js:27:19)
    at ChildProcess.<anonymous> (/opt/linux-remote/node_modules/@linux-remote/session-store/index.js:35:5)
    at ChildProcess.emit (events.js:311:20)
    at finish (internal/child_process.js:861:14)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'ENOMEM',
  code: 'ENOMEM',
  syscall: 'spawn'
}

**Comment by hezedu** [comment]
![t-user](https://user-images.githubusercontent.com/8508437/79330229-c275db80-7f4b-11ea-9dd1-adfb46a9a16a.png)
T user

**Comment by hezedu** [comment]
荷兰  user `_`
