### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by hezedu** [linux-remote/linux-remote#243]
TypeError: cb is not a function
    at process.<anonymous> (/opt/linux-remote/node_modules/@linux-remote/server_main/src/lib/ipc-say.js:28:3)
    at process.emit (events.js:314:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

**Comment by hezedu** [comment]
Fixed by linux-remote/server@fbf096d
