### ISSUE TITLE
开发时偶遇：Unhandled 'error' event[FsSessionStore]

### ISSUE THREAD

**Issue by hezedu** [linux-remote/linux-remote#5]
FsSessionStore memoryTTL start by get session.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)

**Comment by hezedu** [comment]
https://github.com/nodejs/node/issues/13204
